name: vis4ml-datasets
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - backcall=0.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - charset-normalizer=2.0.4
  - comm=0.2.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=2.0.1
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.4
  - ipython=8.12.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.0.4
  - libcurand=10.3.6.39
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.14
  - packaging=24.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0
  - python_abi=3.9
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.32.2
  - scipy=1.11.4
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.3.1
  - torchtriton=2.3.1
  - torchvision=0.18.1
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiofiles==23.2.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - attrs==23.2.0
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - dnspython==2.6.1
      - email-validator==2.1.1
      - exceptiongroup==1.2.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - ffmpy==0.3.2
      - fonttools==4.53.0
      - fsspec==2024.6.0
      - gradio==4.36.1
      - gradio-client==1.0.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - imageio==2.34.1
      - importlib-resources==6.4.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - markdown-it-py==3.0.0
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - opencv-python==4.10.0.84
      - orjson==3.10.5
      - pandas==2.2.2
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pydub==0.25.1
      - pyparsing==3.1.2
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2024.1
      - referencing==0.35.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - ruff==0.4.9
      - scikit-image==0.22.0
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.37.2
      - tifffile==2024.5.22
      - tomlkit==0.12.0
      - toolz==0.12.1
      - tqdm==4.66.4
      - typer==0.12.3
      - tzdata==2024.1
      - ujson==5.10.0
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - watchfiles==0.22.0
      - websockets==11.0.3
      - zipp==3.19.2
